repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 --config tools/.flake8 .
        language: system
        types: [python]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: mypy --config tools/.mypy.ini .
        language: system
        types: [python]
        pass_filenames: false

      - id: isort
        name: isort
        entry: isort --settings-file tools/.isort.cfg .
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        entry: black --config tools/.black .
        language: system
        types: [python]
        pass_filenames: false

      - id: pylint
        name:  pylint
        entry: pylint --rcfile tools/.pylint.rc .
        language: system
        types: [python]
        pass_filenames: false
