services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - pynet

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - pynet

volumes:
  postgres_data:

networks:
  pynet:
    driver: bridge

